### PR TITLE
xir-python: examples

### PR DESCRIPTION
**Pull request by isi-lincoln**
IPython is a requirement for python xir bindings.

lang/python/xir/viz/viz.py:from IPython.core.display import HTML

I've added a requirements file in the xir lang/python directory
that can be used to install the python requirements for xir.

### CODE REVIEW

**Comment by rcgoodfellow** [comment]
So I think we only hit this dependency when using the visualization services from a Jupyter notebook. And I see that this brings in a whole treasure chest of dependencies with it. Think the python language bindings sans Jupyter visualization should work just fine without all these dependencies. I think the better thing to do here is separate out the viz components instead of bringing all their dependencies in.

**Comment by isi-lincoln** [comment]
So all of those are subcomponents of IPython, only thing I installed in virtual environment before freezing.

1. I dont think this addition "changes" anything, it allows for other scripts, such as those in ceftb/engine/build-test-container.sh to call pip install -r requirements.

2.  Although I do agree that a better solution would be a better packaging/self-containment of the visualization components

**Comment by rcgoodfellow** [comment]
I'll trade you a merge for a modularization issue.

**Comment by isi-lincoln** [comment]
Fine by me, in the mean time i'll globally install IPython =)

**Pull request merged**
